name: node_auth
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2

  path: ^1.6.4
  http: ^0.12.0+2
  built_value: ^7.0.0
  tuple: ^1.0.3
  rxdart: ^0.23.1
  image_picker: ^0.6.2+3
  shared_preferences: ^0.5.6

  # my packages
  distinct_value_connectable_stream: ^1.0.3
  flutter_provider: ^1.1.1
  rx_shared_preferences: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.3
  built_value_generator: ^7.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/bg.jpg
   - assets/user.png
