name: node_auth
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+8
  path: ^1.6.4
  http: ^0.12.0+2
  built_value: ^6.7.1
  tuple: ^1.0.3
  shared_preferences: ^0.5.4+1

  # my packages
  distinct_value_connectable_observable: ^2.0.3+1
  flutter_provider: ^1.1.0+3
  rxdart: ^0.22.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.3
  built_value_generator: ^6.7.1

flutter:
  uses-material-design: true
  assets:
   - assets/bg.jpg
   - assets/user.png
