name: node_auth
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  image_picker: ^0.5.3+1
  image: ^2.0.6
  path: ^1.6.2
  http: ^0.12.0+1
  built_value: ^6.3.0
  tuple: ^1.0.2
  rounded_modal: ^1.0.0
  shared_preferences: ^0.5.2

  # my packages
  distinct_value_connectable_observable: ^2.0.0
  flutter_provider: ^1.1.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.3
  built_value_generator: 6.3.0

flutter:
  uses-material-design: true
  assets:
   - assets/bg.jpg
   - assets/user.png
