name: node_auth
description: Simple auth app flutter, server node.js, BLoC pattern, RxDart.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.0

  path: ^1.7.0
  http: ^0.12.2
  built_value: ^7.1.0
  tuple: ^1.0.3
  rxdart: ^0.25.0-beta3
  image_picker: ^0.6.7+12
  shared_preferences: ^0.5.12+4

  distinct_value_connectable_stream: ^1.2.0-beta01
  flutter_provider: ^1.1.1
  rx_shared_preferences: ^1.3.3
  disposebag: ^1.3.2
  flutter_disposebag: ^1.0.0
  flutter_bloc_pattern: ^1.2.0

dependency_overrides:
  rxdart: 0.25.0-beta3

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
  assets:
   - assets/bg.jpg
   - assets/user.png
