name: node_auth
description: Simple auth app flutter, server node.js, BLoC pattern, RxDart.

publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2

  path: ^1.8.0
  http: ^0.13.1
  built_value: ^8.0.4
  tuple: ^2.0.0
  rxdart: ^0.26.0
  image_picker: ^0.7.4
  shared_preferences: ^2.0.5
  octo_image: ^1.0.0+1

  distinct_value_connectable_stream: ^1.2.0
  flutter_provider: ^2.0.0
  rx_shared_preferences: ^2.0.0-nullsafety.0
  disposebag: ^1.5.0
  flutter_disposebag: ^1.1.0
  flutter_bloc_pattern: ^2.0.0
  rxdart_ext: ^0.0.1

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  built_value_generator: ^8.0.4

flutter:
  uses-material-design: true
  assets:
   - assets/bg.jpg
   - assets/user.png
